### ISSUE TITLE
APP: Wyckoff Bulk Generator

### ISSUE THREAD

**Issue by ankitjainmeiitk** [SUNCAT-Center/CatalysisHubFrontend#25]
When I go to Catalysis-Hib.Org and navigate through the app menu to the Wyckoff-Bulk generator, I am not able to remove "1" (default value in the Spacegroup number) field. I can enter spacegroups like 122 but I am not able to change it to 221. I tested this on Firefox and Safari so far and the problem seems to exist on both.

**Comment by mhoffman** [comment]
Fixed in v0.2.9.
